Update first-pipeline

diff --git a/first-pipeline b/first-pipeline
--- a/first-pipeline
+++ b/first-pipeline
@@ -67,3 +67,63 @@ pipeline {
               } 
         }          
 }
+
+#Sample for declaring the environment variables in the pipeline
+pipeline {
+    agent any 
+    
+    environment {
+        FIRSTNAME = 'Yeluri'
+        LASTNAME = 'Venkat'
+     }
+     stages {
+        stage('Build') {
+            steps {
+                sh 'echo $FIRSTNAME $LASTNAME'
+                }
+            }
+        }    
+}
+
+#Simple pipeline code for setting the credentials in jenkins
+pipeline {
+    agent any 
+    environment {
+        secret = credentials('TEST')
+    }
+    stages {
+        stage('Example stage 1') {
+            steps {
+                sh 'echo $secret'
+            }
+       }   
+  }    
+}         
+
+#Sample to update the post actions stesps
+pipeline {
+    agent any
+    stages {
+        stage('Test') {
+            steps {
+                sh 'echo "FAIL!"; exit 1'
+            }
+         }
+     }
+     post {
+        always {
+            echo 'I Will get executed :D'
+        }
+        success {
+            echo 'I will only get executed if this is success'
+        }
+        failure {
+            echo 'I will only get executed if this fails'
+        }
+        unstable {
+            echo 'I will only get executed if this is unstable'
+        }
+   }
+}
+
+        
